### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xuelang7009** [lifeishard4me/Actions#32]
Error: Cannot find module '/home/runner/jd_scripts/jd_plantBean.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Error: Process completed with exit code 1.

**Comment by kerncoola** [comment]
+1
